### ISSUE TITLE
Add error checking for missing columns

### ISSUE THREAD

**Issue by Kchour** [denysvitali/squid_decoder#7]
I didnt have a category for "unfiled" in my notes, so naturally we get the following error: 

`Traceback (most recent call last):
  File "papyrus.py", line 296, in <module>
    notes = getNotes(i[1])
  File "papyrus.py", line 70, in getNotes
    '(SELECT note_uuid FROM notebook_note_association WHERE notebook_uuid=?)', (uuid, ))
sqlite3.OperationalError: no such column: unfiled`

Need to add ability to check which column is available, and only export those

**Comment by denysvitali** [comment]
What version of Squid are you using?

**Comment by hakan-demirli** [comment]
> What version of Squid are you using?

v3.9.3.4 is the version where I have created a backup.

deleting the "unfiled" solves the problem.
https://github.com/denysvitali/squid_decoder/blob/a5992bce40f71b8c22db1efa01ca841c4944f494/papyrus.py#L65

**Comment by denysvitali** [comment]
Can you please make a PR?

**Comment by hakan-demirli** [comment]
> Can you please make a PR?

OK. But, I have also encountered this issue https://github.com/denysvitali/squid_decoder/issues/6. So, I had to make other changes that didn't completely solve the problem but reduced the chance of occurrence, and also I don't know whether those changes including the deletion of the "unfiled", cause any side effects. 
But, if you still want it sure.

And I didn't open another issue for this problem but there is a file limit in python. If you try to export a 1033 page long notebook, you get "Python IO error: too many open files". [Possible solution.](https://stackoverflow.com/questions/6774724/why-python-has-limit-for-count-of-file-handles/28212496#28212496)
